In [ ]:
#擴充套件Numpy-->ndarray
#擴充套件pydantic-->json

#建立ndarray--(1)list->ndarray (2)np.function->ndarray

In [1]:
list_a = [1, 3, 5, 7, 9]
list_b = [3, 5, 6, 7, 9]
list_a + list_b

[1, 3, 5, 7, 9, 3, 5, 6, 7, 9]

In [3]:
#陣列運算
import numpy as np
array_a = np.array([1, 3, 5, 7, 9])
array_b = np.array([3, 5, 6, 7, 9])
type(array_a)
array_a + array_b

array([ 4,  8, 11, 14, 18])

In [64]:
import numpy as np

l = [[1, 2, 3],[2, 3, 4]] #二維的list
array = np.array(l)
array.ndim, array.shape, array.size, 

(2, (2, 3), 6)

In [63]:
import numpy as np
np.random.randn(10,5)

array([[-1.13715915,  0.26486485, -0.09634044, -0.15723493, -0.14879274],
       [ 1.11684808, -1.07166677,  1.2800203 , -1.63439096,  0.91745638],
       [-0.23714341,  1.6864632 ,  1.34247454, -1.20859717, -1.08375971],
       [-2.37041555, -1.40213146, -2.19591652, -1.20517988, -0.19675312],
       [-0.93597697,  1.1315721 ,  1.48480755,  1.09368697, -0.50886741],
       [-0.05064253,  1.36993193,  0.91802816, -0.08163776, -0.51131716],
       [ 0.84079871, -0.69321697, -1.70361562, -0.12965296,  0.59179155],
       [-0.38911199, -0.70859466,  0.88893724, -0.07070821,  2.61598617],
       [-0.16737827,  0.26457451, -0.51667388, -0.20498173, -0.14784392],
       [ 0.56266587,  1.12151539, -0.45749123, -0.03329692, -1.6653066 ]])

In [20]:
#50個學生,每個學生有5個分數
scores = np.random.randint(50,101,size=(50,5)) #min包含 max不包含->M+1
scores

array([[ 85,  63,  57,  79,  79],
       [ 57,  53, 100,  67,  94],
       [ 98,  82,  99,  51,  83],
       [ 97,  74,  95,  96,  89],
       [ 58,  60,  57,  56,  66],
       [ 86,  66,  71,  69,  71],
       [ 62,  65,  74,  85,  69],
       [ 54,  57,  82,  94,  63],
       [ 84,  79,  53,  99,  67],
       [ 95,  61,  53,  97,  56],
       [ 81,  69,  73,  78,  59],
       [ 63,  59,  92,  83,  77],
       [ 94,  67,  68,  62,  70],
       [ 87,  82,  70,  71,  91],
       [ 85, 100,  68,  67,  53],
       [ 90,  68,  96,  55,  50],
       [ 70,  59,  52,  64,  60],
       [ 93,  84,  97,  65,  73],
       [ 70,  95,  84,  84,  69],
       [ 50, 100,  84,  62,  57],
       [ 87,  66,  53,  71,  58],
       [ 77,  85,  56,  62,  60],
       [ 64,  62,  87,  78,  94],
       [ 62,  99,  93,  90,  95],
       [ 82,  50,  59,  78,  79],
       [ 71,  97,  93,  76,  71],
       [ 81,  88,  53,  69,  58],
       [ 96,  53,  89,  68,  96],
       [ 56,  93,  87,  87,  99],
       [ 64,  

In [66]:
#第一個學生
scores[0,:]
#前五個學生
scores[:5,:]
#最後五個學生
scores[-5:,:]

array([[69, 86, 93, 80, 74],
       [79, 59, 86, 64, 82],
       [51, 61, 89, 80, 82],
       [65, 83, 77, 98, 87],
       [63, 63, 72, 96, 85]])

In [68]:
#全班第一科的分數
scores[:,0]
#全班第二科的分數
scores[:,1]

array([ 63,  53,  82,  74,  60,  66,  65,  57,  79,  61,  69,  59,  67,
        82, 100,  68,  59,  84,  95, 100,  66,  85,  62,  99,  50,  97,
        88,  53,  93,  97,  87,  59,  72,  60,  89,  64,  65,  62,  53,
        86,  98, 100,  67,  83,  72,  86,  59,  61,  83,  63])

In [71]:
#每位學生的總分
total = scores[:,0] + scores[:,1] + scores[:,2] + scores[:,3] + scores[:,4]
total

array([363, 371, 413, 451, 297, 363, 355, 350, 382, 362, 360, 374, 361,
       401, 373, 359, 305, 412, 402, 353, 335, 340, 385, 439, 348, 408,
       349, 402, 422, 404, 377, 330, 405, 336, 344, 351, 378, 336, 388,
       318, 385, 397, 417, 367, 330, 402, 370, 363, 410, 379])

In [72]:
#使用統計的方法
#每位學生的總分
np.sum(scores,axis=1)

array([363, 371, 413, 451, 297, 363, 355, 350, 382, 362, 360, 374, 361,
       401, 373, 359, 305, 412, 402, 353, 335, 340, 385, 439, 348, 408,
       349, 402, 422, 404, 377, 330, 405, 336, 344, 351, 378, 336, 388,
       318, 385, 397, 417, 367, 330, 402, 370, 363, 410, 379])

In [73]:
#每位學生的平均
np.mean(scores,axis=1)

array([72.6, 74.2, 82.6, 90.2, 59.4, 72.6, 71. , 70. , 76.4, 72.4, 72. ,
       74.8, 72.2, 80.2, 74.6, 71.8, 61. , 82.4, 80.4, 70.6, 67. , 68. ,
       77. , 87.8, 69.6, 81.6, 69.8, 80.4, 84.4, 80.8, 75.4, 66. , 81. ,
       67.2, 68.8, 70.2, 75.6, 67.2, 77.6, 63.6, 77. , 79.4, 83.4, 73.4,
       66. , 80.4, 74. , 72.6, 82. , 75.8])